function function_f=Phi_fun(variables_v,parameters)
BETA=parameters(1);
GAMMA=parameters(2);
ALPHA=parameters(3);
RHO=parameters(4);
DELTA=parameters(5);
SIGMA=parameters(6);
logk=variables_v(1,:);
loga=variables_v(2,:);
function_f=zeros(1,size(variables_v,2));
function_f(1,:)=RHO.*loga;
